import 'dart:io';

import 'package:get_cli/common/utils/logger/LogUtils.dart';
import 'package:get_cli/common/utils/pubspec/pubspec_utils.dart';
import 'package:get_cli/functions/routes/get_app_pages.dart';
import 'package:get_cli/functions/find_file/find_file_by_name.dart';
import 'package:get_cli/samples/impl/get_route.dart';
import 'package:recase/recase.dart';
import 'package:version/version.dart';

Future<void> addRoute(String nameRoute, String path) async {
  File routesFile = findFileByName('app_routes.dart');
  if (routesFile == null) {
    await RouteSample().create();
    routesFile = File(RouteSample().path);
  }
  List<String> pathSplit = path.split('/');
  pathSplit.removeLast();
  pathSplit.removeWhere((element) => element == 'app' || element == 'modules');
  bool supportChildren = Version.parse('3.21.1')
          .compareTo(PubspecUtils.getPackageVersion('get')) <=
      0;
  if (supportChildren) {
    pathSplit.clear();
  }
  pathSplit.add(nameRoute);
  for (var i = 0; i < pathSplit.length; i++) {
    pathSplit[i] =
        pathSplit[i].snakeCase.snakeCase.toLowerCase().replaceAll('_', '-');
  }
  String route = pathSplit.join('/');
  List<String> lines = routesFile.readAsLinesSync();
  String line =
      "\tstatic const ${nameRoute.snakeCase.toUpperCase()} = '/$route';";
  if (lines.contains(line)) {
    return;
  }
  while (lines.last.isEmpty) {
    /* remove the blank lines at the end of the file
     generated by visual studio and other ide
     */
    lines.removeLast();
  }
  // formatting the file to the standard format
  /// Example
  /// before
  /// ```
  /// {
  ///   static const HOME = '/home';}
  /// ```
  /// after
  /// ```
  /// {
  ///   static const HOME = '/home';
  /// }
  /// ```
  if (lines.last.trim() != '}') {
    lines.last = lines.last.replaceAll('}', '');
    lines.add('}');
  }

  lines.insert(lines.length - 1, line);

  await routesFile.writeAsStringSync(lines.join('\n'));
  LogService.success('${nameRoute} route created successfully,');

  await addAppPage(nameRoute, path);
}
